#
# roots global preferences
# (edit carefully)
#

# runs under the alias `roots pkg`
# options: bower, cdnjs
package_manager: bower

# for use with `roots new`
# `roots new example` will use `default`
# `roots new example --min` will use `min`
templates: 
  default: default
  min: min
  basic: basic
  blog: blog
  ejs: ejs
  express: express
  min: min